// GENERATED by scripts/build-font-metrics.mjs — do not edit by hand.
import type { FaceId, FaceMetrics } from "../fonts";
import playfairR from "./playfair-r.json";
import playfairB from "./playfair-b.json";
import playfairI from "./playfair-i.json";
import playfairBI from "./playfair-bi.json";
import cormorantR from "./cormorant-r.json";
import cormorantB from "./cormorant-b.json";
import cormorantI from "./cormorant-i.json";
import cormorantBI from "./cormorant-bi.json";
import loraR from "./lora-r.json";
import loraB from "./lora-b.json";
import loraI from "./lora-i.json";
import loraBI from "./lora-bi.json";
import cinzelR from "./cinzel-r.json";
import cinzelB from "./cinzel-b.json";
import montserratR from "./montserrat-r.json";
import montserratB from "./montserrat-b.json";
import montserratI from "./montserrat-i.json";
import montserratBI from "./montserrat-bi.json";
import poppinsR from "./poppins-r.json";
import poppinsB from "./poppins-b.json";
import poppinsI from "./poppins-i.json";
import poppinsBI from "./poppins-bi.json";
import greatvibesR from "./greatvibes-r.json";
import pinyonR from "./pinyon-r.json";

export const METRICS: Record<FaceId, FaceMetrics> = {
  "playfair-r": playfairR,
  "playfair-b": playfairB,
  "playfair-i": playfairI,
  "playfair-bi": playfairBI,
  "cormorant-r": cormorantR,
  "cormorant-b": cormorantB,
  "cormorant-i": cormorantI,
  "cormorant-bi": cormorantBI,
  "lora-r": loraR,
  "lora-b": loraB,
  "lora-i": loraI,
  "lora-bi": loraBI,
  "cinzel-r": cinzelR,
  "cinzel-b": cinzelB,
  "montserrat-r": montserratR,
  "montserrat-b": montserratB,
  "montserrat-i": montserratI,
  "montserrat-bi": montserratBI,
  "poppins-r": poppinsR,
  "poppins-b": poppinsB,
  "poppins-i": poppinsI,
  "poppins-bi": poppinsBI,
  "greatvibes-r": greatvibesR,
  "pinyon-r": pinyonR,
};
